version: '3'

services:
   web:
      container_name: flask-machine-learning-api
      hostname: flask-machine-learning-api
      build: .
      ports:
         - "5000:5000"
      volumes:
         - .:/src